# Generated by Django 5.2.6 on 2025-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0002_rename_citeria_badge_criteria_remove_group_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='name',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('1k', '1 Kilometer'), ('2k', '2 Kilometers'), ('5k', '5 Kilometers'), ('10k', '10 Kilometers'), ('20k', '20 Kilometers'), ('40k', '40 Kilometers'), ('100k', '100 Kilometers')], default='1k', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
