# Generated by Django 5.2.6 on 2025-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_photo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
